$fn=120;
H=14;
difference()
{
    union()
    {
        hull()
        {
             cylinder(d=10,h=1);
             rotate([0,0,45])translate([0,0,3])minkowski()
             {
                cube([3,3,1],center=true);
                cylinder(r=5,h=0.1);
             }
        }
        cylinder(d=5.5,h=H-0.01);
    }
    translate([0,0,H-1.5])cube([2.25,2.25,4],center=true);
}