#!/bin/csh -f

echo 'target_add_binary_data(Remote.elf "icons/favicon.ico" BINARY)' > icons/CMakeLists.txt
rm -f main/icons.m
foreach f (icons/*.png)
	if("$f:t:r" != "favicon") then
		echo 'target_add_binary_data(Remote.elf "'"$f"'" BINARY)' >> icons/CMakeLists.txt
		if("$f:t:r" != "apple-touch-icon") then
			echo 'icon('"$f:t:r"');' >> main/icons.m
		endif
	endif
end
